--Usuwanie
--Usuwanie Tabel
DROP TABLE H_REZERWACJA;
DROP TABLE H_POKOJ;
DROP TABLE H_GOSC;
DROP TABLE H_PRACOWNIK;
DROP TABLE H_ZMIANA;
DROP TABLE H_PARKING;
DROP TABLE H_ADRES;

--Usuwanie sekwencji numerowania
DROP SEQUENCE Auto_Num_H_ZMIANA;
DROP SEQUENCE Auto_Num_H_ADRES;
DROP SEQUENCE Auto_Num_H_PARKING;
DROP SEQUENCE Auto_Num_H_GOSC;
DROP SEQUENCE Auto_Num_H_POKOJ;
DROP SEQUENCE Auto_Num_H_PRACOWNIK;
DROP SEQUENCE Auto_Num_H_REZERWACJA;

--Tabele
--Tabela Zmiana
CREATE TABLE H_ZMIANA(
	Zmiana_ID NUMBER( 6,0) PRIMARY KEY,
	Nr_Zmiany NUMBER( 2,0) NOT NULL,
	Start_Zmiany VARCHAR2( 5) NOT NULL,
	Koniec_Zmiany VARCHAR2( 5) NOT NULL, 
	Uwagi VARCHAR2( 32) DEFAULT 'Brak'
);

--Tabela Adres
CREATE TABLE H_ADRES(
	Adres_ID NUMBER( 6,0) PRIMARY KEY,
	Kraj VARCHAR2( 32) NOT NULL,
	Miasto VARCHAR2( 32) NOT NULL,
	Ulica VARCHAR2( 32) NOT NULL,
	Nr_Domu NUMBER( 6,0) NOT NULL,
	Kod_Pocztowy VARCHAR2( 6) NOT NULL,

	CHECK( Nr_Domu > 0)
);

--Tabela Parking
CREATE TABLE H_PARKING(
	Parking_ID NUMBER( 6,0) PRIMARY KEY,
	Numer_Miejsca NUMBER( 2,0) NOT NULL,
	Pietro NUMBER( 2,0) NOT NULL,
	Nazwa VARCHAR2( 32) NOT NULL,
	Adres_ID NUMBER( 6,0) NOT NULL
);

--Tabela Gosc
CREATE TABLE H_GOSC(
	Gosc_ID NUMBER( 6,0) PRIMARY KEY,
	Imie VARCHAR2( 32) CHECK( Imie != 'Imie' AND Imie IS NOT NULL),
	Nazwisko VARCHAR2( 32) CHECK( Nazwisko != 'Nazwisko' AND Nazwisko IS NOT NULL),
	Nr_Dowodu CHAR( 9) UNIQUE CHECK( LENGTH( Nr_Dowodu) = 9),
	Adres_ID NUMBER( 6,0) NOT NULL
);

--Tabela Pracownik
CREATE TABLE H_PRACOWNIK(
	Pracownik_ID Numeric( 6,0) PRIMARY KEY,
	Imie VARCHAR2( 32) NOT NULL,
	Nazwisko VARCHAR2( 32) NOT NULL,
	Nr_Dowodu CHAR( 9) UNIQUE CHECK( LENGTH( Nr_Dowodu) = 9),
	Data_Zatrudnienia DATE NOT NULL,
	Data_Zwolnienia DATE,
	Adres_ID NUMBER( 6,0) NOT NULL,
	Zmiana_ID NUMBER( 6,0) NOT NULL,
	
	CHECK( Data_Zatrudnienia > Data_Zwolnienia)
);

--Tabela Pokoj	
CREATE TABLE H_POKOJ(
	POKOJ_ID NUMBER( 6,0) PRIMARY KEY,
	NR_POKOJU NUMBER( 6,0) UNIQUE NOT NULL,
	NR_PIETRA NUMBER( 6,0) NOT NULL,
	POJEMNOSC NUMBER( 6,0) NOT NULL,
	CENA NUMBER( 6,2) NOT NULL CHECK( CENA > 0)
);

--Tabela rezerwacja
CREATE TABLE H_REZERWACJA(
	Rezerwacja_ID  NUMBER( 6,0) PRIMARY KEY,
	Od_Kiedy DATE NOT NULL,
	Do_Kiedy DATE NOT NULL,
	Gosc_ID NUMBER( 6,0) NOT NULL,	
	Pokoj_ID NUMBER( 6,0) NOT NULL,
	Parking_ID NUMBER( 6,0),
	Pracownik_ID NUMBER( 6,0) NOT NULL,
	
	CHECK( Od_Kiedy < Do_Kiedy)
);

--Klucze obce
--FK do Parking z adres
ALTER TABLE H_PARKING 
	ADD FOREIGN KEY( Adres_ID)
	REFERENCES H_ADRES( Adres_ID) 
	ON DELETE CASCADE;
	
--FK do Gosc z adres
ALTER TABLE H_GOSC 
	ADD FOREIGN KEY( Adres_ID)
	REFERENCES H_ADRES( Adres_ID) 
	ON DELETE CASCADE;

--FK do Pracownik z Adres
ALTER TABLE H_PRACOWNIK 
	ADD FOREIGN KEY( Adres_ID)
	REFERENCES H_ADRES( Adres_ID) 
	ON DELETE CASCADE;
	
--FK do Pracownik z Zmiany
ALTER TABLE H_PRACOWNIK 
	ADD FOREIGN KEY( Zmiana_ID)
	REFERENCES H_ZMIANA( Zmiana_ID) 
	ON DELETE CASCADE;

--FK do Rezerwacji z goscia
ALTER TABLE H_REZERWACJA
	ADD FOREIGN KEY( Gosc_ID)
	REFERENCES H_GOSC( Gosc_ID)
	ON DELETE CASCADE;

--FK do Rezerwacji z pokoju
ALTER TABLE H_REZERWACJA
	ADD FOREIGN KEY( Pokoj_ID)
	REFERENCES H_POKOJ( Pokoj_ID)
	ON DELETE CASCADE;

--FK do Rezerwacji z parkingu
ALTER TABLE H_REZERWACJA
	ADD FOREIGN KEY( Parking_ID)
	REFERENCES H_PARKING( Parking_ID)
	ON DELETE CASCADE;

--FK do Rezerwacji z pracownika
ALTER TABLE H_REZERWACJA
	ADD FOREIGN KEY( Pracownik_ID)
	REFERENCES H_PRACOWNIK( Pracownik_ID)
	ON DELETE CASCADE;	
	
--Sequence autonumerowanie
--Sequence do H_ZMIANA
CREATE SEQUENCE Auto_Num_H_ZMIANA
	MINVALUE  1
	MAXVALUE  10000
	INCREMENT BY 1
	START WITH 1
	NOCACHE  NOORDER  NOCYCLE;

--Sequence do H_ADRES
CREATE SEQUENCE Auto_Num_H_ADRES
	MINVALUE  1
	MAXVALUE  10000
	INCREMENT BY 1
	START WITH 1
	NOCACHE  NOORDER  NOCYCLE;

--Sequence do H_PARKING
CREATE SEQUENCE Auto_Num_H_PARKING
	MINVALUE  1
	MAXVALUE  10000
	INCREMENT BY 1
	START WITH 1
	NOCACHE  NOORDER  NOCYCLE;

--Sequence do H_GOSC
CREATE SEQUENCE Auto_Num_H_GOSC
	MINVALUE  1
	MAXVALUE  10000
	INCREMENT BY 1
	START WITH 1
	NOCACHE  NOORDER  NOCYCLE;

--Sequence do H_PRACOWNIK
CREATE SEQUENCE Auto_Num_H_PRACOWNIK
	MINVALUE  1
	MAXVALUE  10000
	INCREMENT BY 1
	START WITH 1
	NOCACHE  NOORDER  NOCYCLE;

--Sequence do H_POKOJ
CREATE SEQUENCE Auto_Num_H_POKOJ
	MINVALUE  1
	MAXVALUE  10000
	INCREMENT BY 1
	START WITH 1
	NOCACHE  NOORDER  NOCYCLE;

--Sequence do H_REZERWACJA
CREATE SEQUENCE Auto_Num_H_REZERWACJA
	MINVALUE  1
	MAXVALUE  10000
	INCREMENT BY 1
	START WITH 1
	NOCACHE  NOORDER  NOCYCLE;
	
--Dane do tabeli pokoj
--pierwsze pietro
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 1001, 1, 2, 200.50);

INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 1002, 1, 2, 200.50);

INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 1003, 1, 2, 200.50);

INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 1004, 1, 2, 200.50);

INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 1005, 1, 2, 200.50);

INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 1006, 1, 2, 200.50);

INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 1007, 1, 2, 200.50);

INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 1008, 1, 2, 200.50);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 1009, 1, 2, 200.50);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 1010, 1, 2, 200.50);
	
--drugie pietro
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 2001, 2, 4, 530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 2002, 2, 4, 530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 2003, 2, 4, 530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 2004, 2, 4, 530);

INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 2005, 2, 4, 530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 2006, 2, 4, 530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 2007, 2, 4, 530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 2008, 2, 4, 530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 2009, 2, 4, 530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 2010, 2, 4, 530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 2011, 2, 4, 530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 2012, 2, 4, 530);
	
--trzecie pietro
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3001, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3002, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3003, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3004, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3005, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3006, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3007, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3008, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3009, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3010, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3011, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3012, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3013, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3014, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3015, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3016, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3017, 3, 1, 1530);
	
INSERT INTO H_POKOJ
	VALUES( Auto_Num_H_POKOJ.NEXTVAL, 3018, 3, 1, 1530);
	
--Dane do tabeli zmiana
INSERT INTO H_ZMIANA
	VALUES( Auto_Num_H_ZMIANA.NEXTVAL, 1, '00:00', '08:00', 'Nie spac');
	
INSERT INTO H_ZMIANA
	VALUES( Auto_Num_H_ZMIANA.NEXTVAL, 2, '04:00', '12:00', DEFAULT);
	
INSERT INTO H_ZMIANA
	VALUES( Auto_Num_H_ZMIANA.NEXTVAL, 3, '06:00', '14:00', DEFAULT);

INSERT INTO H_ZMIANA
	VALUES( Auto_Num_H_ZMIANA.NEXTVAL, 4, '08:00', '16:00', DEFAULT);	
	
INSERT INTO H_ZMIANA
	VALUES( Auto_Num_H_ZMIANA.NEXTVAL, 5, '10:00', '18:00', DEFAULT);
	
INSERT INTO H_ZMIANA
	VALUES( Auto_Num_H_ZMIANA.NEXTVAL, 6, '12:00', '20:00', DEFAULT);
	
INSERT INTO H_ZMIANA
	VALUES( Auto_Num_H_ZMIANA.NEXTVAL, 7, '14:00', '22:00', 'Zachowac szczegolna ostroznosc');	

INSERT INTO H_ZMIANA
	VALUES( Auto_Num_H_ZMIANA.NEXTVAL, 8, '16:00', '24:00', 'Zachowac szczegolna ostroznosc');
	
--Dane do tabeli adres
INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Rzeszow', 'Wojska Polskiego', 12, '14-142' );
	
INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Rzeszow', 'Armii Krajowej', 32, '14-142' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Sosnowiec', 'Brzozowa', 1, '85-427' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Sosnowiec', 'Debowa', 2, '85-427' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Sosnowiec', 'Lipowa', 3, '85-427' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Sosnowiec', 'Patolowa', 33, '85-427' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Radom', 'Radomska', 7, '69-112' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Radom', 'Chytra', 8,'69-112' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Radom', 'Babowa', 22, '69-112' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Radom', 'Chytrosci', 9, '69-112' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Warszawa', 'Kamienicka', 1, '62-589' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Warszawa', 'Sloikowa', 12, '62-589' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Warszawa', 'Zamkowa', 23, '62-589' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Warszawa', 'Warszawska', 13, '62-589' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Warszawa', 'Prosta', 14, '62-589' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Bydgoszcz', 'Prawa', 23, '45-288' );	
	
INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Bydgoszcz', 'Kanciasta', 14, '45-288' );
	
INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Bydgoszcz', 'Lewa', 1, '45-288' );
	
INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Bydgoszcz', 'Slonecznikowa', 12, '45-288' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Bydgoszcz', 'Piaskowa', 33, '45-288' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Poznan', 'Kosciuszkiego', 43, '62-400' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Poznan', 'Karmelowa', 36, '62-400' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Poznan', 'Czerwona', 65, '62-400' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Poznan', 'Niebieska', 54, '62-400' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Poznan', 'Karynskiego', 43, '62-400' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Bialystok', 'Uniwersytecka', 32, '21-542' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Bialystok', 'Zachodnia', 25, '21-542' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Bialystok', 'Brzozowa', 46, '21-542' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Bialystok', 'Rynkowa', 31, '21-542' );

INSERT INTO H_ADRES
	VALUES( Auto_Num_H_ADRES.NEXTVAL, 'Polska', 'Bialystok', 'Szkolna', 69, '21-542' );
	
--Dane do tabeli parking
INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 1, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 2, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 3, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 4, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 5, 0, 'Parking przed Hotelem', 1);
	
INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 6, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 7, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 8, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 9, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 10, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 11, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 12, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 13, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 14, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 15, 0, 'Parking przed Hotelem', 1);	

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 16, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 17, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 18, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 19, 0, 'Parking przed Hotelem', 1);

INSERT INTO H_PARKING
	VALUES( Auto_Num_H_PARKING.NEXTVAL, 20, 0, 'Parking przed Hotelem', 1);
	
--Dane do tabeli Gosc
INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Adam', 'Nowak', '987563483', 2);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Kamil', 'Wisniewski', '987523483', 3);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Krystian', 'Lewandowski', '937563483', 4);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Kamila', 'Szymanska', '987163483',  5);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Edward', 'Wozniak', '981563483',  6);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Mikalaj', 'Pililipaits', '480513283',  6);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Anna', 'Nowak', '587563483',  7);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Grazyna', 'Dabrowska', '927563483',  8);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Helena', 'Kozlowska', '921563483',  9);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Ewa', 'Kozlowska', '983124483',  10);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Maria', 'Mazur', '987451253',  1);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Krzysztof', 'Mazur', '123423483',  11);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Zofia', 'Mazur', '953242383',  11);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Marek', 'Mazur', '134353483',  11);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Grzegorz', 'Piotrowski', '523463483',  12);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Teresa', 'Piotrowska', '975234453',  12);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Magdalena', 'Grabowska', '785468674',  13);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Tadeusz', 'Grabowski', '764337563',  13);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Irena', 'Krol', '343623583',  14);

INSERT INTO H_GOSC	
	VALUES( Auto_Num_H_GOSC.NEXTVAL, 'Mariusz', 'Wrobel', '456573125',  15);
	
--Dane do tabeli pracownik
INSERT INTO H_PRACOWNIK
	VALUES( Auto_Num_H_PRACOWNIK.NEXTVAL, 'Adam', 'Nowak', '945641354', TO_DATE('11-11-2018', 'DD-MM-YYYY'), NULL, 16, 1);
	
INSERT INTO H_PRACOWNIK
	VALUES( Auto_Num_H_PRACOWNIK.NEXTVAL, 'Krystian', 'Wozniak', '912451583', TO_DATE('11-11-2018', 'DD-MM-YYYY'), NULL, 17, 2);
	
INSERT INTO H_PRACOWNIK
	VALUES( Auto_Num_H_PRACOWNIK.NEXTVAL, 'Kamil', 'Narczak', '124551483', TO_DATE('11-11-2018', 'DD-MM-YYYY'), NULL, 18, 3);
	
INSERT INTO H_PRACOWNIK
	VALUES( Auto_Num_H_PRACOWNIK.NEXTVAL, 'Kondrad', 'Kernik', '254322483', TO_DATE('11-11-2018', 'DD-MM-YYYY'), NULL, 19, 4);
	
INSERT INTO H_PRACOWNIK
	VALUES( Auto_Num_H_PRACOWNIK.NEXTVAL, 'Weronika', 'Potok', '146143343', TO_DATE('11-11-2018', 'DD-MM-YYYY'), NULL, 20, 5);
	
INSERT INTO H_PRACOWNIK
	VALUES( Auto_Num_H_PRACOWNIK.NEXTVAL, 'Kamila', 'Miciniak', '763545673', TO_DATE('11-11-2018', 'DD-MM-YYYY'), NULL, 20, 1);
	
INSERT INTO H_PRACOWNIK
	VALUES( Auto_Num_H_PRACOWNIK.NEXTVAL, 'Helga', 'Nardok', '745648127', TO_DATE('11-11-2018', 'DD-MM-YYYY'), NULL, 21, 2);
	
INSERT INTO H_PRACOWNIK
	VALUES( Auto_Num_H_PRACOWNIK.NEXTVAL, 'Marek', 'Hamburk', '745797672', TO_DATE('11-11-2018', 'DD-MM-YYYY'), NULL, 22, 6);

INSERT INTO H_PRACOWNIK
	VALUES( Auto_Num_H_PRACOWNIK.NEXTVAL, 'Piotr', 'Kowalski', '286103894', TO_DATE('11-11-2018', 'DD-MM-YYYY'), NULL, 23, 7);

INSERT INTO H_PRACOWNIK
	VALUES( Auto_Num_H_PRACOWNIK.NEXTVAL, 'Marta', 'Reczniak', '879157821', TO_DATE('11-11-2018', 'DD-MM-YYYY'), NULL, 24, 8);
	
--Dane do tabeli rezerwacja
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '11-11-2018', 'DD-MM-YYYY'), TO_DATE( '16-11-2018', 'DD-MM-YYYY'), 8, 27, NULL, 1);

INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '11-11-2018', 'DD-MM-YYYY'), TO_DATE( '16-11-2018', 'DD-MM-YYYY'), 17, 10, NULL, 1);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '11-11-2018', 'DD-MM-YYYY'), TO_DATE( '16-11-2018', 'DD-MM-YYYY'), 18, 10, NULL, 1);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '21-01-2018', 'DD-MM-YYYY'), TO_DATE( '16-02-2018', 'DD-MM-YYYY'), 10, 9, 3, 1);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '21-01-2018', 'DD-MM-YYYY'), TO_DATE( '16-02-2018', 'DD-MM-YYYY'), 9, 9, 2, 1);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '11-01-2018', 'DD-MM-YYYY'), TO_DATE( '19-01-2018', 'DD-MM-YYYY'), 19, 25, NULL, 1);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '11-02-2018', 'DD-MM-YYYY'), TO_DATE( '16-02-2018', 'DD-MM-YYYY'), 3, 32, NULL, 1);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '11-03-2018', 'DD-MM-YYYY'), TO_DATE( '11-04-2018', 'DD-MM-YYYY'), 13, 21, 1, 2);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '11-03-2018', 'DD-MM-YYYY'), TO_DATE( '11-04-2018', 'DD-MM-YYYY'), 14, 21, NULL, 2);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '11-03-2018', 'DD-MM-YYYY'), TO_DATE( '11-04-2018', 'DD-MM-YYYY'), 12, 21, 4, 2);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '11-03-2018', 'DD-MM-YYYY'), TO_DATE( '11-04-2018', 'DD-MM-YYYY'), 11, 21, NULL, 2);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '13-02-2018', 'DD-MM-YYYY'), TO_DATE( '17-02-2018', 'DD-MM-YYYY'), 1, 8, 5, 2);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '13-02-2018', 'DD-MM-YYYY'), TO_DATE( '17-02-2018', 'DD-MM-YYYY'), 7, 8, NULL, 2);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '11-01-2018', 'DD-MM-YYYY'), TO_DATE( '16-01-2018', 'DD-MM-YYYY'), 16, 7, NULL, 3);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '11-01-2018', 'DD-MM-YYYY'), TO_DATE( '16-01-2018', 'DD-MM-YYYY'), 15, 7, NULL, 3);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '11-02-2018', 'DD-MM-YYYY'), TO_DATE( '11-03-2018', 'DD-MM-YYYY'), 4, 24, NULL, 3);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '11-01-2018', 'DD-MM-YYYY'), TO_DATE( '15-01-2018', 'DD-MM-YYYY'), 2, 23, 6, 3);
	
INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '01-03-2018', 'DD-MM-YYYY'), TO_DATE( '31-03-2018', 'DD-MM-YYYY'), 5, 6, 7, 3);

INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '01-03-2018', 'DD-MM-YYYY'), TO_DATE( '31-03-2018', 'DD-MM-YYYY'), 6, 6, NULL, 3);

INSERT INTO H_REZERWACJA
	VALUES( Auto_Num_H_REZERWACJA.NEXTVAL, TO_DATE( '01-01-2018', 'DD-MM-YYYY'), TO_DATE( '01-06-2018', 'DD-MM-YYYY'), 20, 26, NULL, 3);